[package]
name = "wgpu3DFlockingSimulation"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = { version = "1.24.0", features = ["derive"] }
crossterm = "0.29.0"
futures-intrusive = "0.5.0"
pollster = "0.4.0"
rand = "0.9.2"
wgpu = "28.0.0"
